models:
  etl-pipeline-case:        
    staging:
      +materialized: view
      +dataset: stg
    core:
      +materialized: table
      +dataset: core
    marts:
      +materialized: table
      +dataset: marts
