version: 2

models:
 
  - name: fct_order
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: customer_id
      - name: payment_status
        tests:
          - accepted_values:
              values: ['paid', 'unpaid']
      - name: net_revenue
        tests:
          - not_null


  - name: fct_shipment
    columns:
      - name: shipment_id
        tests:
          - not_null
          - unique
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fct_order')     
              field: order_id
      - name: latest_status
        tests:
          - not_null
      - name: delivered_at
        tests:
          # sadece teslim edilenlerde null olmasın
          - not_null:
              where: "latest_status = 'DELIVERED'"


  - name: fct_marketing_spend
    columns:
      - name: date
        tests:
          - not_null
      - name: channel
        tests:
          - not_null
      - name: spend_try
        tests:
          - not_null
      - name: clicks
        tests:
          - not_null


  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: signup_date
        tests:
          - not_null
      - name: city
        tests:
          - not_null
      - name: district
        tests:
          - not_null
